"""biblatex datamodel: which fields each entry type legally accepts.

Validity is derived from biblatex's formal datamodel (data/biblatex_datamodel.json,
generated by tools/gen_datamodel.py from blx-dm.def) rather than a hand-kept
blocklist, so it stays complete and standard. Legacy BibTeX field/type names are
resolved through aliases so ordinary .bib usage is not false-flagged.
"""

import json
import os

_DATA = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                     "data", "biblatex_datamodel.json")

# Legacy BibTeX field names biber accepts as aliases of biblatex datamodel
# fields. Without these, standard .bib usage ('journal', 'school') would be
# flagged as invalid against the pure biblatex datamodel.
FIELD_ALIASES = {
    "journal": "journaltitle", "school": "institution",
    "address": "location", "place": "location",   # both are biber aliases of location
    "annote": "annotation", "archiveprefix": "eprinttype",
    "primaryclass": "eprintclass", "key": "sortkey",
}

# Used if the data file is absent, so the tool still runs.
_DM_FALLBACK = {
    "aliases": {"phdthesis": "thesis", "mastersthesis": "thesis",
                "conference": "inproceedings", "techreport": "report"},
    "entrytypes": ["article", "book", "booklet", "inbook", "incollection",
                   "inproceedings", "manual", "misc", "online", "proceedings",
                   "report", "thesis", "unpublished", "collection", "patent",
                   "periodical", "software", "dataset", "phdthesis",
                   "mastersthesis", "conference", "techreport"],
    "universal": ["author", "title", "year", "doi", "url", "note", "eprint",
                  "eprinttype", "eprintclass", "month", "addendum", "pubstate",
                  "language", "keywords", "abstract", "date", "editor"],
    "bytype": {"article": ["journal", "journaltitle", "volume", "number",
                           "pages", "issn", "issue", "eid"],
               "book": ["publisher", "volume", "isbn", "edition", "series"],
               "inproceedings": ["booktitle", "publisher", "pages", "series",
                                 "eventtitle", "venue"],
               "thesis": ["institution", "type", "pages"],
               "report": ["institution", "type", "number"],
               "misc": ["howpublished", "organization"]},
}


# Mandatory-field constraints, used only if the data file is absent. Mirrors
# biblatex's \DeclareDatamodelConstraints (a slot is satisfied by ANY of its
# fields). Year is intentionally NOT here -- biber does not mandate it.
_MANDATORY_FALLBACK = {
    "article": [["author"], ["journaltitle"], ["title"]],
    "book": [["author"], ["title"]],
    "inbook": [["author"], ["title"], ["booktitle"]],
    "incollection": [["author"], ["editor"], ["title"], ["booktitle"]],
    "collection": [["editor"], ["title"]],
    "booklet": [["author", "editor"], ["title"]],
    "online": [["title"], ["url", "doi", "eprint"]],
    "misc": [["title"]], "manual": [["title"]], "dataset": [["title"]],
    "proceedings": [["title"]],
    "inproceedings": [["author"], ["title"], ["booktitle"]],
    "report": [["author"], ["title"], ["type"], ["institution"]],
    "thesis": [["author"], ["title"], ["type"], ["institution"]],
    "patent": [["author"], ["title"], ["number"]],
    "unpublished": [["author"], ["title"]],
}
_DM_FALLBACK["mandatory"] = _MANDATORY_FALLBACK


def _load_datamodel():
    try:
        with open(_DATA, encoding="utf-8") as fh:
            dm = json.load(fh)
    except (OSError, json.JSONDecodeError):
        dm = _DM_FALLBACK
    universal = set(dm.get("universal", []))
    bytype = {t: set(f) for t, f in dm.get("bytype", {}).items()}
    aliases = dm.get("aliases", {})
    entrytypes = set(dm.get("entrytypes", [])) | set(bytype) | set(aliases)
    mandatory = dm.get("mandatory", {}) or _MANDATORY_FALLBACK
    return universal, bytype, aliases, entrytypes, mandatory


DM_UNIVERSAL, DM_BYTYPE, DM_ALIASES, DM_ENTRYTYPES, DM_MANDATORY = _load_datamodel()


def legal_fields(etype):
    """Set of fields the biblatex datamodel allows for an entry type (universal
    fields plus the type's own), resolving legacy BibTeX type aliases. Empty set
    means the type is unknown to the datamodel -- caller should not flag."""
    t = DM_ALIASES.get(etype, etype)
    specific = DM_BYTYPE.get(t)
    if specific is None:
        return set()
    return DM_UNIVERSAL | specific


def mandatory_slots(etype):
    """biblatex's mandatory-field constraint for an entry type, as a list of slots
    (each a list of acceptable field names; ANY one satisfies the slot). Resolves
    legacy type aliases. Empty list means no constraint is known for the type."""
    return DM_MANDATORY.get(DM_ALIASES.get(etype, etype), [])
